// <auto-generated />
using System;
using LMSDALLibrary.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LMSDALLibrary.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20260515065606_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "borrowing_status_enum", new[] { "active", "returned" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "copy_status_enum", new[] { "available", "borrowed", "unavailable", "damaged" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "fine_status_enum", new[] { "unpaid", "paid", "waived" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "membership_type_enum", new[] { "basic", "premium", "student" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LMSModelLibrary.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("book_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BookId"));

                    b.Property<string>("BookAuthor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("book_author");

                    b.Property<int>("BookCategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("book_category_id");

                    b.Property<string>("BookTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("book_title");

                    b.HasKey("BookId")
                        .HasName("book_pkey");

                    b.HasIndex(new[] { "BookAuthor" }, "idx_book_author");

                    b.HasIndex(new[] { "BookCategoryId" }, "idx_book_category");

                    b.HasIndex(new[] { "BookTitle" }, "idx_book_title");

                    b.ToTable("book", (string)null);
                });

            modelBuilder.Entity("LMSModelLibrary.Models.BookCategory", b =>
                {
                    b.Property<int>("BookCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("book_category_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BookCategoryId"));

                    b.Property<string>("BookCategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("book_category_name");

                    b.HasKey("BookCategoryId")
                        .HasName("book_category_pkey");

                    b.HasIndex(new[] { "BookCategoryName" }, "book_category_book_category_name_key")
                        .IsUnique();

                    b.ToTable("book_category", (string)null);
                });

            modelBuilder.Entity("LMSModelLibrary.Models.BookCopy", b =>
                {
                    b.Property<int>("BookCopyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("book_copy_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BookCopyId"));

                    b.Property<int>("BookId")
                        .HasColumnType("integer")
                        .HasColumnName("book_id");

                    b.Property<int>("CopyStatus")
                        .HasColumnType("integer");

                    b.HasKey("BookCopyId")
                        .HasName("book_copy_pkey");

                    b.HasIndex(new[] { "BookId" }, "idx_book_copy_book");

                    b.ToTable("book_copy", (string)null);
                });

            modelBuilder.Entity("LMSModelLibrary.Models.Borrowing", b =>
                {
                    b.Property<int>("BorrowingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("borrowing_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BorrowingId"));

                    b.Property<int>("BookCopyId")
                        .HasColumnType("integer")
                        .HasColumnName("book_copy_id");

                    b.Property<DateOnly>("BorrowDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("borrow_date")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<int>("BorrowingStatus")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<int>("MemberId")
                        .HasColumnType("integer")
                        .HasColumnName("member_id");

                    b.Property<DateOnly?>("ReturnDate")
                        .HasColumnType("date")
                        .HasColumnName("return_date");

                    b.HasKey("BorrowingId")
                        .HasName("borrowing_pkey");

                    b.HasIndex("BookCopyId");

                    b.HasIndex(new[] { "MemberId" }, "idx_borrowing_member");

                    b.ToTable("borrowing", (string)null);
                });

            modelBuilder.Entity("LMSModelLibrary.Models.Fine", b =>
                {
                    b.Property<int>("FineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("fine_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FineId"));

                    b.Property<int>("BorrowingId")
                        .HasColumnType("integer")
                        .HasColumnName("borrowing_id");

                    b.Property<decimal>("FineAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("fine_amount");

                    b.Property<int>("FinePaidStatus")
                        .HasColumnType("integer");

                    b.HasKey("FineId")
                        .HasName("fine_pkey");

                    b.HasIndex(new[] { "BorrowingId" }, "fine_borrowing_id_key")
                        .IsUnique();

                    b.ToTable("fine", (string)null);
                });

            modelBuilder.Entity("LMSModelLibrary.Models.FinePayment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("payment_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaymentId"));

                    b.Property<int>("FineId")
                        .HasColumnType("integer")
                        .HasColumnName("fine_id");

                    b.Property<decimal>("FinePaidAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("fine_paid_amount");

                    b.Property<int>("MemberId")
                        .HasColumnType("integer")
                        .HasColumnName("member_id");

                    b.Property<DateTime>("PaidDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("paid_date")
                        .HasDefaultValueSql("now()");

                    b.HasKey("PaymentId")
                        .HasName("fine_payment_pkey");

                    b.HasIndex("FineId");

                    b.HasIndex(new[] { "MemberId" }, "idx_fine_payment_member");

                    b.ToTable("fine_payment", (string)null);
                });

            modelBuilder.Entity("LMSModelLibrary.Models.Member", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("member_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MemberId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("MemberEmail")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("member_email");

                    b.Property<string>("MemberName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("member_name");

                    b.Property<string>("MemberPhone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("member_phone");

                    b.Property<int>("MembershipTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("membership_type_id");

                    b.HasKey("MemberId")
                        .HasName("member_pkey");

                    b.HasIndex("MembershipTypeId");

                    b.HasIndex(new[] { "MemberEmail" }, "idx_member_email");

                    b.HasIndex(new[] { "MemberPhone" }, "idx_member_phone");

                    b.HasIndex(new[] { "MemberEmail" }, "member_member_email_key")
                        .IsUnique();

                    b.HasIndex(new[] { "MemberPhone" }, "member_member_phone_key")
                        .IsUnique();

                    b.ToTable("member", (string)null);
                });

            modelBuilder.Entity("LMSModelLibrary.Models.MembershipType", b =>
                {
                    b.Property<int>("MembershipTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("membership_type_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MembershipTypeId"));

                    b.Property<int>("MaxActiveBorrowings")
                        .HasColumnType("integer")
                        .HasColumnName("max_active_borrowings");

                    b.Property<int>("MaxBorrowDays")
                        .HasColumnType("integer")
                        .HasColumnName("max_borrow_days");

                    b.Property<int>("MembershipTypeName")
                        .HasColumnType("integer");

                    b.HasKey("MembershipTypeId")
                        .HasName("membership_type_pkey");

                    b.ToTable("membership_type", (string)null);
                });

            modelBuilder.Entity("LMSModelLibrary.Models.Book", b =>
                {
                    b.HasOne("LMSModelLibrary.Models.BookCategory", "BookCategory")
                        .WithMany("Books")
                        .HasForeignKey("BookCategoryId")
                        .IsRequired()
                        .HasConstraintName("fk_book_category");

                    b.Navigation("BookCategory");
                });

            modelBuilder.Entity("LMSModelLibrary.Models.BookCopy", b =>
                {
                    b.HasOne("LMSModelLibrary.Models.Book", "Book")
                        .WithMany("BookCopies")
                        .HasForeignKey("BookId")
                        .IsRequired()
                        .HasConstraintName("fk_book_copy_book");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("LMSModelLibrary.Models.Borrowing", b =>
                {
                    b.HasOne("LMSModelLibrary.Models.BookCopy", "BookCopy")
                        .WithMany("Borrowings")
                        .HasForeignKey("BookCopyId")
                        .IsRequired()
                        .HasConstraintName("fk_borrowing_book_copy");

                    b.HasOne("LMSModelLibrary.Models.Member", "Member")
                        .WithMany("Borrowings")
                        .HasForeignKey("MemberId")
                        .IsRequired()
                        .HasConstraintName("fk_borrowing_member");

                    b.Navigation("BookCopy");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("LMSModelLibrary.Models.Fine", b =>
                {
                    b.HasOne("LMSModelLibrary.Models.Borrowing", "Borrowing")
                        .WithOne("Fine")
                        .HasForeignKey("LMSModelLibrary.Models.Fine", "BorrowingId")
                        .IsRequired()
                        .HasConstraintName("fk_fine_borrowing");

                    b.Navigation("Borrowing");
                });

            modelBuilder.Entity("LMSModelLibrary.Models.FinePayment", b =>
                {
                    b.HasOne("LMSModelLibrary.Models.Fine", "Fine")
                        .WithMany("FinePayments")
                        .HasForeignKey("FineId")
                        .IsRequired()
                        .HasConstraintName("fk_fine_payment_fine");

                    b.HasOne("LMSModelLibrary.Models.Member", "Member")
                        .WithMany("FinePayments")
                        .HasForeignKey("MemberId")
                        .IsRequired()
                        .HasConstraintName("fk_fine_payment_member");

                    b.Navigation("Fine");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("LMSModelLibrary.Models.Member", b =>
                {
                    b.HasOne("LMSModelLibrary.Models.MembershipType", "MembershipType")
                        .WithMany("Members")
                        .HasForeignKey("MembershipTypeId")
                        .IsRequired()
                        .HasConstraintName("fk_member_membership_type");

                    b.Navigation("MembershipType");
                });

            modelBuilder.Entity("LMSModelLibrary.Models.Book", b =>
                {
                    b.Navigation("BookCopies");
                });

            modelBuilder.Entity("LMSModelLibrary.Models.BookCategory", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("LMSModelLibrary.Models.BookCopy", b =>
                {
                    b.Navigation("Borrowings");
                });

            modelBuilder.Entity("LMSModelLibrary.Models.Borrowing", b =>
                {
                    b.Navigation("Fine");
                });

            modelBuilder.Entity("LMSModelLibrary.Models.Fine", b =>
                {
                    b.Navigation("FinePayments");
                });

            modelBuilder.Entity("LMSModelLibrary.Models.Member", b =>
                {
                    b.Navigation("Borrowings");

                    b.Navigation("FinePayments");
                });

            modelBuilder.Entity("LMSModelLibrary.Models.MembershipType", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
